#This file contains individual examples and tests of filtering criteria
#Unless specified otherwise, it's possible to mix and match the different filters to obtain a more complicated query
#The filtering queries return a list of issue previews, these previews do not contain all of the information of an issue

### Get specific Issue in its entirety
@id = 1
GET http://localhost:8080/api/issues/{{id}}

###
#Useful variables for filters
@pageNumber = "0"
@pageSize = "10"
@sortType = "CREATION_DATE_ASCENDING"

### F1: Filter by type
POST http://localhost:8080/api/issues/search
Content-Type: application/json

{
  "pageNumber": {{pageNumber}},
  "pageSize": {{pageSize}},
  "sortType": {{sortType}},
  "filters": {
    "type": "BUG"
  }
}

### F2: Filter by status
POST http://localhost:8080/api/issues/search
Content-Type: application/json

{
  "filters": {
    "status": "INPROGRESS"
  }
}

### F3: Filter by priority
POST http://localhost:8080/api/issues/search
Content-Type: application/json

{
  "filters": {
    "priority": true
  }
}

### F3: Filter by reporting user
POST http://localhost:8080/api/issues/search
Content-Type: application/json

{
  "filters": {
    "reportingUserId": 1
  }
}

### F4: Filter by assigned status (i.e. is the issue assigned to a user or not)
# This filter is incompatible with F5
POST http://localhost:8080/api/issues/search
Content-Type: application/json

{
  "filters": {
    "isAssigned": false
  }
}

### F5: Filter by assigned user
# This filter is incompatible with F4
POST http://localhost:8080/api/issues/search
Content-Type: application/json

{
  "filters": {
    "assignedUserId": 1
  }
}

### F6: Filter by presence of an image
POST http://localhost:8080/api/issues/search
Content-Type: application/json

{
  "filters": {
    "hasImage": false
  }
}

### F7: Filter by presence of tags
# This filter is not compatible with F8
POST http://localhost:8080/api/issues/search
Content-Type: application/json

{
  "filters": {
    "isTagged": false
  }
}

### F8: Filter by set of tags
# This filter is not compatible with F7
POST http://localhost:8080/api/issues/search
Content-Type: application/json

{
  "filters": {
    "tags": ["Graphics", "Frontend"]
  }
}

### F9: Filter by creation date start
#Use with F10 to create a creation date range: end date should be after start date
#Use T00:00:00 for the start date to include entire day
POST http://localhost:8080/api/issues/search
Content-Type: application/json

{
  "filters": {
    "startCreationDate": "2026-05-12T00:00:00"
  }
}

### F10: Filter by creation date end
#Use with F9 to create a creation date range: end date should be after start date
#Use T23:59:59 for the end date to include entire day
POST http://localhost:8080/api/issues/search
Content-Type: application/json

{
  "filters": {
    "endCreationDate": "2026-05-12T23:59:59"
  }
}

### F11: Filter by last modified date start
#Use with F12 to create a last modified date range: end date should be after start date
#Use T00:00:00 for the start date to include entire day
POST http://localhost:8080/api/issues/search
Content-Type: application/json

{
  "filters": {
    "startLastModifiedDate": "2026-05-12T00:00:00"
  }
}

### F12: Filter by last modified date end
#Use with F11 to create a last modified date range: end date should be after start date
#Use T23:59:59 for the end date to include entire day
POST http://localhost:8080/api/issues/search
Content-Type: application/json

{
  "filters": {
    "endLastModifiedDate": "2026-05-12T23:59:59"
  }
}

### F13: No filters applied
POST http://localhost:8080/api/issues/search
Content-Type: application/json

{
}