### 1. Crea l'admin
POST http://localhost:8080/api/users
Content-Type: application/json

{
  "mail": "ciao",
  "username": "Pippo",
  "rawPassword": "password",
  "repeatRawPassword": "password",
  "role": "ADMIN"
}

### 2. Login con admin
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "mail": "ciao",
  "rawPassword": "password"
}

> {% client.global.set("auth_token", response.body.token) %}

### 3. Controllo se ho il login
GET http://localhost:8080/api/users/me
Authorization: Bearer {{auth_token}}

### 4. Crea issue 1
POST http://localhost:8080/api/issues
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "title": "MiaIssue1",
  "description": "Midsdfhdfghdfgsfasda",
  "image": "No",
  "priority": false,
  "tags": ["CIaonE"],
  "type": "BUG"
}

### 5. Crea issue 2
POST http://localhost:8080/api/issues
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "title": "MiaIssue2",
  "description": "Miasdfsdgsgdsgsda",
  "priority": false,
  "tags": ["Ciaone"],
  "type": "BUG"
}

### 6. Visualizza issues
GET http://localhost:8080/api/issues
Authorization: Bearer {{auth_token}}

### 7. Chiude issue duplicata
PUT http://localhost:8080/api/issues/close
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "status": "",
  "newStatus": "TODO"
}