# Creates initial admin and other additional users, an admin is saved in admin_auth_token, a user is saved in user_auth_token
run userCreation.http

###
#Create some tags to use in issueCreation
run tagsCreation.http

###
#Creates some issues
run issueCreation.http

###
#Collection of different Filtering and Sorting arrangements
run issueFiltering.http

### Check if I have login
GET http://localhost:8080/api/users/me
Authorization: Bearer {{admin_auth_token}}

### View tags
GET http://localhost:8080/api/tags
Authorization: Bearer {{admin_auth_token}}

### Assign issue
PUT http://localhost:8080/api/issues/assign
Authorization: Bearer {{admin_auth_token}}
Content-Type: application/json

{
  "issueId": 1,
  "userId": 1
}

### View all issues
GET http://localhost:8080/api/issues
Authorization: Bearer {{admin_auth_token}}

### Close "duplicated" issue
PUT http://localhost:8080/api/issues/close
Authorization: Bearer {{admin_auth_token}}
Content-Type: application/json

{
  "issueId": 1
}

### View users by availability
GET http://localhost:8080/api/users/available
Authorization: Bearer {{admin_auth_token}}

### Update issue status
PUT http://localhost:8080/api/issues/status
Authorization: Bearer {{admin_auth_token}}
Content-Type: application/json

{
  "issueId": 1,
  "newStatus": "INPROGRESS"
}

### View issue history
@issueId = 1
GET http://localhost:8080/api/issues/{{issueId}}/history
Authorization: Bearer {{admin_auth_token}}
